### ISSUE TITLE
Connect button not authenticating

### ISSUE THREAD

**Issue by efox1010** [v-braun/GCConnection#1]
I have one question around the "connect" button. Currently that is not doing anything for me. I have to go into settings and turn on game center in order to authenticate. After i have turned GC on in settings it automatically authenticates every time I open the app. Was the "connect" button intended to log the user in via game center, if they are not already signed in? If so can you tell me what I am missing because I think thats awesome and would love to implement that into my app. 

Thanks!

**Comment by v-braun** [comment]
Hi ✌️& sorry for the late answer!

The _connect_ button calls the **authenticate()** [method](https://github.com/v-braun/GCConnection/blob/4f51f1f578f7ad7465e870cf76d34eecf25fc0d8/GCConnection/ViewController.swift#L23).
The same method will be also called on app start in [AppDelegate](https://github.com/v-braun/GCConnection/blob/4f51f1f578f7ad7465e870cf76d34eecf25fc0d8/GCConnection/AppDelegate.swift#L19).
I added it to demonstrate two ways how you can authenticate (or connect) the user against the GameCenter:
1.: On app start, the user will be authenticated and until your app loads you get a response from the GC. I prefer to do that in my apps. In the most cases the login will be successful and when your start screen is loaded the user is already authenticated. The [authhandler](https://github.com/v-braun/GCConnection/blob/4f51f1f578f7ad7465e870cf76d34eecf25fc0d8/GCConnection/ViewController.swift#L163)  should be called and you can show user related informations.

2.: You can start your app and add an additional connect button, where the user has explicit to connect the the GC. This is one touch more than the user have to do. I personally never add such a button to my apps.

It is strange that you have to go to the settings and enable GC explicit. It is now some time ago, but if I remember it correctly a login form should be shown when you connect to the GC (by calling _authenticate_). This will only be shown once! And you have to enable the GC support in your plist file (see screen below). If you cannot reproduce this, I would suggest to reset your simulator device (or choose one that you never used).

![image](https://user-images.githubusercontent.com/4738210/60011533-3fad2880-967a-11e9-8848-b97939ceb9a7.png)

**Comment by efox1010** [comment]
You’re awesome, I’m currently in the process of moving this week. I’ll reach back once I get settled and try implementing. Thanks again. 

- Eric Fox

**Comment by efox1010** [comment]
Hello again,

I'm trying to use your send/receive data code for a simple game of tic tac toe between two players and cannot figure out how to get the game to work for two players who are connected. The game works but is completely separate for each player ie. one player makes a move and only see's it on their screen. 

So, in short I'm having trouble sending and receiving data.  Any help here would be great! Screen shots of my code are attached. Thanks again for the awesome code. Let me know if you have questions as or need more info in order to help me out!


![Screen Shot 2019-05-21 at 8 19 32 PM](https://user-images.githubusercontent.com/37758861/61422385-11191b00-a8d1-11e9-8c9f-7cce492245a1.png)
![Screen Shot 2019-05-21 at 8 19 50 PM](https://user-images.githubusercontent.com/37758861/61422386-12e2de80-a8d1-11e9-97fe-6d50578270c3.png)

**Comment by v-braun** [comment]
Hi!
Have you any output in the console?
Is the connection of the clients established successfull?
I had also some problems for connecting clients when they are not in the same network.
In Theory that should also work but sometimes you are behind a firewall that blocks this kind of connection requests (this is only an assumption). Could not find any information from apple on that problem but you see this kind of connection problems in your console.

**Comment by efox1010** [comment]
Hello! Attached are screen shots from my apps console and yours. Nearly
identical.

The only difference in console output I am seeing is the last line on mine
which does not pop up every time and everything I've found online is that
you should not worry about it. I'm more worried my code for sending and
receiving data is a bit off?

In regards to being on the same name network...this should, in theory, be
able to connect people on separate networks possibly across the world
correct?

Again, really appreciate the help!

**Comment by v-braun** [comment]
Sorry I don't see any attachments on your post!

**Comment by efox1010** [comment]
My apologies, I responded using gmail and the images did not come though. They should now be attached!
![Screen Shot 2019-07-20 at 10 47 56 PM](https://user-images.githubusercontent.com/37758861/61586732-ae2dbb00-ab40-11e9-8478-466a9d48623c.png)
<img width="804" alt="Screen Shot 2019-07-18 at 11 20 56 PM" src="https://user-images.githubusercontent.com/37758861/61586738-d4ebf180-ab40-11e9-9900-5098a97adc67.png">

**Comment by v-braun** [comment]
It looks for me that the connection is not successfull established. The errors (RemoveNominatedCandidatePair, etc.) looks very strange for me. 
Maybe you could create a support ticket at apple. This lib is a wrapper around their APIs and make it easier to create the connection

**Comment by efox1010** [comment]
Sounds good! I’ll report back my findings with Apple. Thanks!

- Eric Fox

**Comment by v-braun** [comment]
initial question was answered
